<?php

$estados_usa = array(
    array('id' => 1, 'estado' => 'Alabama'),
    array('id' => 2, 'estado' => 'Alaska'),
    array('id' => 1, 'estado' => 'Arizona'),
    array('id' => 2, 'estado' => 'Arkansas'),
    array('id' => 1, 'estado' => 'California'),
    array('id' => 2, 'estado' => 'Colorado'),
    array('id' => 1, 'estado' => 'Connecticut'),
    array('id' => 2, 'estado' => 'Delaware'),
    array('id' => 1, 'estado' => 'Florida'),
    array('id' => 2, 'estado' => 'Georgia'),
    array('id' => 1, 'estado' => 'Hawaii'),
    array('id' => 2, 'estado' => 'Idaho'),
    array('id' => 1, 'estado' => 'Illinois'),
    array('id' => 2, 'estado' => 'Indiana'),
    array('id' => 1, 'estado' => 'Iowa'),
    array('id' => 2, 'estado' => 'Kansas'),
    array('id' => 1, 'estado' => 'Kentucky'),
    array('id' => 2, 'estado' => 'Louisiana'),
    array('id' => 1, 'estado' => 'Maine'),
    array('id' => 2, 'estado' => 'Maryland'),
    array('id' => 1, 'estado' => 'Massachusetts'),
    array('id' => 2, 'estado' => 'Michigan'),
    array('id' => 1, 'estado' => 'Minnesota'),
    array('id' => 2, 'estado' => 'Mississippi'),
    array('id' => 1, 'estado' => 'Missouri'),
    array('id' => 2, 'estado' => 'Montana'),
    array('id' => 1, 'estado' => 'Nebraska'),
    array('id' => 2, 'estado' => 'Nevada'),
    array('id' => 1, 'estado' => 'New Hampshire'),
    array('id' => 2, 'estado' => 'New Jersey'),
    array('id' => 1, 'estado' => 'New Mexico'),
    array('id' => 2, 'estado' => 'New York'),
    array('id' => 1, 'estado' => 'North Carolina'),
    array('id' => 2, 'estado' => 'North Dakota'),
    array('id' => 1, 'estado' => 'Ohio'),
    array('id' => 2, 'estado' => 'Oklahoma'),
    array('id' => 1, 'estado' => 'Oregon'),
    array('id' => 2, 'estado' => 'Pennsylvania'),
    array('id' => 1, 'estado' => 'Rhode Island'),
    array('id' => 2, 'estado' => 'South Carolina'),
    array('id' => 1, 'estado' => 'South Dakota'),
    array('id' => 2, 'estado' => 'Tennessee'),
    array('id' => 1, 'estado' => 'Texas'),
    array('id' => 2, 'estado' => 'Utah'),
    array('id' => 1, 'estado' => 'Vermont'),
    array('id' => 2, 'estado' => 'Virginia'),
    array('id' => 1, 'estado' => 'Washington'),
    array('id' => 2, 'estado' => 'West Virginia'),
    array('id' => 1, 'estado' => 'Wisconsin'),
    array('id' => 2, 'estado' => 'Wyoming'),
);



?>
